# modified from https://github.com/sgl-project/sglang/blob/main/.github/ISSUE_TEMPLATE/1-bug-report.yml
name: 🐞 Bug report
description: Create a report to help us reproduce and fix the bug
title: "[Bug] "
labels: ['Bug']
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: 1. I have searched for related issues and FAQs (https://nunchaku.tech/docs/nunchaku/faq/faq.html) but was unable to find a solution.
        - label: 2. The issue persists in the latest version.
        - label: 3. Please note that without environment information and a minimal reproducible example, it will be difficult for us to reproduce and address the issue, which may delay our response.
        - label: 4. If your report is a question rather than a bug, please submit it as a discussion at https://github.com/mit-han-lab/nunchaku/discussions/new/choose. Otherwise, this issue will be closed.
        - label: 5. If this is related to ComfyUI, please report it at https://github.com/mit-han-lab/ComfyUI-nunchaku/issues.
        - label: 6. I will do my best to describe the issue in English.
  - type: textarea
    attributes:
      label: Describe the Bug
      description: Provide a clear and concise explanation of the bug you encountered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Please include relevant environment details such as your system specifications, Python version, PyTorch version, and CUDA version.
      placeholder: "Example: Ubuntu 24.04, Python 3.11, PyTorch 2.6, CUDA 12.4"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction Steps
      description: |
        What command or script did you execute? Which **model** were you using?
      placeholder: "Example: python run_model.py --config config.json"
    validations:
      required: true
